// list of animals sorted alphabetically pulled from
// https://github.com/adzialocha/random-animal-name-generator/blob/master/animals.json
/// List of 1750 animal names
const List<String> all_animals = [
  "aardvark",
  "aardwolf",
  "abalone",
  "abyssinian cat",
  "abyssinian ground hornbill",
  "acacia rat",
  "achilles tang",
  "acorn barnacle",
  "acorn weevil",
  "acorn woodpecker",
  "acouchi",
  "adams stag horned beetle",
  "addax",
  "adder",
  "adelie penguin",
  "admiral butterfly",
  "adouri",
  "aegean cat",
  "affenpinscher",
  "afghan hound",
  "african augur buzzard",
  "african bush viper",
  "african civet",
  "african clawed frog",
  "african elephant",
  "african fish eagle",
  "african golden cat",
  "african ground hornbill",
  "african harrier hawk",
  "african hornbill",
  "african jacana",
  "african mole snake",
  "african paradise flycatcher",
  "african pied kingfisher",
  "african porcupine",
  "african rock python",
  "african wildcat",
  "african wild dog",
  "agama",
  "agouti",
  "aidi",
  "airedale",
  "airedale terrier",
  "akita inu",
  "alabama map turtle",
  "alaska jingle",
  "alaskan husky",
  "alaskan klee kai",
  "alaskan malamute",
  "albacore tuna",
  "albatross",
  "albertosaurus",
  "albino",
  "aldabra tortoise",
  "allen's big eared bat",
  "alleycat",
  "alligator",
  "alligator gar",
  "alligator snapping turtle",
  "allosaurus",
  "alpaca",
  "alpinegoat",
  "alpine roadguide tiger beetle",
  "altiplano chinchilla mouse",
  "amazon dolphin",
  "amazon parrot",
  "amazon tree boa",
  "amber penshell",
  "ambush bug",
  "american alligator",
  "american avocet",
  "american badger",
  "american bittern",
  "american black vulture",
  "american bobtail",
  "american bulldog",
  "american cicada",
  "american crayfish",
  "american cream draft",
  "american crocodile",
  "american crow",
  "american curl",
  "americangoldfinch",
  "american indian horse",
  "american kestrel",
  "american lobster",
  "american marten",
  "american paint horse",
  "american quarter horse",
  "american rat snake",
  "american red squirrel",
  "american river otter",
  "american robin",
  "american saddlebred",
  "american shorthair",
  "american toad",
  "american warmblood",
  "american wigeon",
  "american wirehair",
  "amethyst gem clam",
  "amethystine python",
  "amethyst sunbird",
  "ammonite",
  "amoeba",
  "amphibian",
  "amphiuma",
  "amur minnow",
  "amur ratsnake",
  "amur starfish",
  "anaconda",
  "anchovy",
  "andalusian horse",
  "andean cat",
  "andeancockoftherock",
  "andean condor",
  "anemone",
  "anemone crab",
  "anemone shrimp",
  "angelfish",
  "angel wing mussel",
  "anglerfish",
  "angora",
  "angwantibo",
  "anhinga",
  "ankole",
  "ankole watusi",
  "anna's hummingbird",
  "annelid",
  "annelida",
  "anole",
  "anopheles mosquito",
  "ant",
  "antarctic fur seal",
  "antarctic giant petrel",
  "antbear",
  "anteater",
  "antelope",
  "antelope ground squirrel",
  "antipodes green parakeet",
  "antlion",
  "anura",
  "aoudad",
  "apatosaurus",
  "ape",
  "aphid",
  "apis dorsata laboriosa",
  "aplomado falcon",
  "appaloosa",
  "aquatic leech",
  "arabian horse",
  "arabian oryx",
  "arabian wildcat",
  "aracari",
  "arachnid",
  "arowana",
  "archaeocete",
  "archaeopteryx",
  "archerfish",
  "arctic duck",
  "arctic fox",
  "arctic hare",
  "arctic seal",
  "arctic wolf",
  "argali",
  "argentine horned frog",
  "argentine ruddy duck",
  "argus fish",
  "ariel toucan",
  "arizona alligator lizard",
  "arkshell",
  "armadillo",
  "armed crab",
  "armed nylon shrimp",
  "armyant",
  "armyworm",
  "arowana",
  "arrow crab",
  "arrow worm",
  "arthropods",
  "aruanas",
  "asian constable butterfly",
  "asian damselfly",
  "asian elephant",
  "asian lion",
  "asian pied starling",
  "asian porcupine",
  "asian small clawed otter",
  "asian trumpetfish",
  "asian water buffalo",
  "asiatic greater freshwater clam",
  "asiatic lesser freshwater clam",
  "asiatic mouflon",
  "asiaticwildass",
  "asp",
  "ass",
  "assassin bug",
  "astarte",
  "astrangia coral",
  "atlantic black goby",
  "atlantic blue tang",
  "atlantic ridley turtle",
  "atlantic sharpnose puffer",
  "atlantic spadefish",
  "atlas moth",
  "attwatersprairiechicken",
  "auk",
  "auklet",
  "aurochs",
  "australian cattle dog",
  "australian curlew",
  "australian freshwater crocodile",
  "australian fur seal",
  "australian kelpie",
  "australian kestrel",
  "australian shelduck",
  "australian silky terrier",
  "austrian pinscher",
  "avians",
  "avocet",
  "axis deer",
  "axolotl",
  "aye aye",
  "aztecant",
  "azure vase",
  "azure vase sponge",
  "azure winged magpie",
  "babirusa",
  "baboon",
  "backswimmer",
  "bactrian",
  "badger",
  "bagworm",
  "baiji",
  "bald eagle",
  "baleen whale",
  "balloonfish",
  "ball python",
  "bandicoot",
  "bangeltiger",
  "bantam rooster",
  "banteng",
  "barasingha",
  "barasingha",
  "barb",
  "barbet",
  "barebirdbat",
  "barnacle",
  "barn owl",
  "barnswallow",
  "barracuda",
  "basenji",
  "basil",
  "basilisk",
  "bass",
  "basset hound",
  "bat",
  "bats",
  "beagle",
  "bear",
  "bearded collie",
  "bearded dragon",
  "beauceron",
  "beaver",
  "bedbug",
  "bedlington terrier",
  "bee",
  "beetle",
  "bellfrog",
  "bellsnake",
  "beluga whale",
  "bengal tiger",
  "berger picard",
  "bernese mountain dog",
  "betta fish",
  "bettong",
  "bichon frise",
  "bighorn",
  "bighorn sheep",
  "bighorn sheep",
  "big mouth bass",
  "bilby",
  "billygoat",
  "binturong",
  "bird",
  "bird of paradise",
  "bison",
  "bittern",
  "black and tan coonhound",
  "blackbear",
  "blackbird",
  "blackbuck",
  "black crappie",
  "blackfish",
  "blackfly",
  "black footed ferret",
  "blacklab",
  "black lemur",
  "black mamba",
  "black norwegian elkhound",
  "black panther",
  "black rhino",
  "black russian terrier",
  "black widow spider",
  "blesbok",
  "blobfish",
  "blowfish",
  "blueandgoldmackaw",
  "bluebird",
  "bluebottle",
  "bluebottle jellyfish",
  "blue breasted kookaburra",
  "bluefin tuna",
  "bluefish",
  "bluegill",
  "bluejay",
  "blue morpho butterfly",
  "blue shark",
  "bluet",
  "bluetick coonhound",
  "bluetongue lizard",
  "blue whale",
  "boa",
  "boa constrictor",
  "boar",
  "bobcat",
  "bobolink",
  "bobwhite",
  "boll weevil",
  "bongo",
  "bonobo",
  "booby",
  "border collie",
  "border terrier",
  "borer",
  "borzoi",
  "boto",
  "boubou",
  "boutu",
  "bovine",
  "brahman bull",
  "brahman cow",
  "brant",
  "bream",
  "brocket deer",
  "bronco",
  "brontosaurus",
  "brown bear",
  "brown butterfly",
  "bubblefish",
  "buck",
  "buckeye butterfly",
  "budgie",
  "bufeo",
  "buffalo",
  "bufflehead",
  "bug",
  "bull",
  "bullfrog",
  "bullmastiff",
  "bumblebee",
  "bunny",
  "bunting",
  "burro",
  "bushbaby",
  "bush squeaker",
  "bustard",
  "butterfly",
  "buzzard",
  "caecilian",
  "caiman",
  "caiman lizard",
  "calf",
  "camel",
  "canadagoose",
  "canary",
  "canine",
  "canvasback",
  "cape ghost frog",
  "capybara",
  "caracal",
  "cardinal",
  "caribou",
  "carp",
  "carpenter ant",
  "cassowary",
  "cat",
  "catbird",
  "caterpillar",
  "catfish",
  "cats",
  "cattle",
  "caudata",
  "cavy",
  "centipede",
  "cero",
  "chafer",
  "chameleon",
  "chamois",
  "chanticleer",
  "cheetah",
  "chevrotain",
  "chick",
  "chickadee",
  "chicken",
  "chihuahua",
  "chimneyswift",
  "chimpanzee",
  "chinchilla",
  "chinese crocodile lizard",
  "chipmunk",
  "chital",
  "chrysalis",
  "chrysomelid",
  "chuckwalla",
  "chupacabra",
  "cicada",
  "cirriped",
  "civet",
  "clam",
  "cleaner wrasse",
  "clingfish",
  "clown anemonefish",
  "clumber",
  "coati",
  "cob",
  "cobra",
  "cock",
  "cockatiel",
  "cockatoo",
  "cocker spaniel",
  "cockroach",
  "cod",
  "coelacanth",
  "collared lizard",
  "collie",
  "colt",
  "comet",
  "comma butterfly",
  "common gonolek",
  "conch",
  "condor",
  "coney",
  "conure",
  "cony",
  "coot",
  "cooter",
  "copepod",
  "copper butterfly",
  "copperhead",
  "coqui",
  "coral",
  "cormorant",
  "cornsnake",
  "corydoras catfish",
  "cottonmouth",
  "cottontail",
  "cougar",
  "cow",
  "cowbird",
  "cowrie",
  "coyote",
  "coypu",
  "crab",
  "crane",
  "cranefly",
  "crayfish",
  "creature",
  "cricket",
  "crocodile",
  "crocodile skink",
  "crossbill",
  "crow",
  "sölustjórastarfi",
  "crustacean",
  "cub",
  "cuckoo",
  "cur",
  "curassow",
  "curlew",
  "couscous",
  "cusimanse",
  "cuttlefish",
  "cutworm",
  "cygnet",
  "dachshund",
  "daddy long legs",
  "dairy cow",
  "dalmatian",
  "damselfly",
  "danish swedish farmdog",
  "darkling beetle",
  "dartfrog",
  "darwin's fox",
  "dassie",
  "dassie rat",
  "david's tiger",
  "deer",
  "deer mouse",
  "degu",
  "degus",
  "deinonychus",
  "desert pupfish",
  "devilfish",
  "devil tasmanian",
  "diamondback rattlesnake",
  "dik dik",
  "dikkops",
  "dingo",
  "dinosaur",
  "diplodocus",
  "dipper",
  "discus",
  "doberman pinscher",
  "doctorfish",
  "dodo",
  "dodo bird",
  "doe",
  "dog",
  "dogfish",
  "dogwood club gall",
  "dogwood twig borer",
  "dolphin",
  "donkey",
  "dorado",
  "dore",
  "dorking",
  "dormouse",
  "dotterel",
  "douglas fir bark beetle",
  "dove",
  "dowitcher",
  "draft horse",
  "dragon",
  "dragonfly",
  "drake",
  "drever",
  "dromaeosaur",
  "dromedary",
  "drongo",
  "duck",
  "duckbill cat",
  "duckbill platypus",
  "duckling",
  "dugong",
  "duiker",
  "dungbeetle",
  "dungeness crab",
  "dunlin",
  "dunnart",
  "dutch shepherd dog",
  "dutch smoushond",
  "dwarf mongoose",
  "dwarf rabbit",
  "eagle",
  "earthworm",
  "earwig",
  "eastern glass lizard",
  "eastern newt",
  "easteuropeanshepherd",
  "eastrussiancoursinghounds",
  "east siberian laika",
  "echidna",
  "eel",
  "eel elephant",
  "eevee",
  "eft",
  "egg",
  "egret",
  "eider",
  "eidolon helvum",
  "ekaltadeta",
  "eland",
  "electric eel",
  "elephant",
  "elephant beetle",
  "elephant seal",
  "elk",
  "elkhound",
  "elver",
  "emerald tree skink",
  "emperor penguin",
  "emperor shrimp",
  "emu",
  "english pointer",
  "english setter",
  "equestrian",
  "equine",
  "erin",
  "ermine",
  "erne",
  "eskimo dog",
  "esok",
  "estuarine crocodile",
  "ethiopian wolf",
  "european fire salamander",
  "european polecat",
  "ewe",
  "eyas",
  "eyelash pit viper",
  "eyra",
  "fairy bluebird",
  "fairyfly",
  "falcon",
  "fallow deer",
  "fantail",
  "fan worms",
  "fat tailed dunnart",
  "fawn",
  "feline",
  "fennec fox",
  "ferret",
  "fiddler crab",
  "fieldmouse",
  "field spaniel",
  "finch",
  "finnish spitz",
  "fin whale",
  "fireant",
  "fire bellied toad",
  "firecrest",
  "firefly",
  "fish",
  "fishing cat",
  "flamingo",
  "flat coat retriever",
  "flatfish",
  "flea",
  "flee",
  "flicker",
  "flickertail squirrel",
  "flies",
  "flounder",
  "fluke",
  "fly",
  "flycatcher",
  "flying fish",
  "flying fox",
  "flying lemur",
  "flying squirrel",
  "foal",
  "fossa",
  "fowl",
  "fox",
  "foxhound",
  "fox terrier",
  "french bulldog",
  "freshwater eel",
  "frigatebird",
  "frilled lizard",
  "frill necked lizard",
  "fritillary butterfly",
  "frog",
  "frogmouth",
  "fruit bat",
  "fruit fly",
  "fugu",
  "fulmar",
  "funnel weaver spider",
  "fur seal",
  "gadwall",
  "galago",
  "galah",
  "galapagos albatross",
  "galapagos dove",
  "galapagos hawk",
  "galapagos mockingbird",
  "galapagos penguin",
  "galapagos sea lion",
  "galapagos tortoise",
  "gallinule",
  "galloway cow",
  "gander",
  "ganges dolphin",
  "gannet",
  "gar",
  "garden snake",
  "garpike",
  "garter snake",
  "gaur",
  "gavial",
  "gazelle",
  "gecko",
  "geese",
  "gelada",
  "gelding",
  "gemsbok",
  "gemsbuck",
  "genet",
  "gentoo penguin",
  "gerbil",
  "gerenuk",
  "german pinscher",
  "german shepherd",
  "german shorthaired pointer",
  "german spaniel",
  "german spitz",
  "german wirehaired pointer",
  "gharial",
  "ghostshrimp",
  "giant schnauzer",
  "gibbon",
  "gila monster",
  "giraffe",
  "glassfrog",
  "globefish",
  "glowworm",
  "gnat",
  "gnatcatcher",
  "gnu",
  "goa",
  "goat",
  "godwit",
  "goitered",
  "goldeneye",
  "golden mantled ground squirrel",
  "golden retriever",
  "goldfinch",
  "goldfish",
  "gonolek",
  "goose",
  "goosefish",
  "gopher",
  "goral",
  "gordonsetter",
  "gorilla",
  "goshawk",
  "gosling",
  "gossamer winged butterfly",
  "gourami",
  "grackle",
  "grasshopper",
  "grass spider",
  "gray fox",
  "grayling",
  "gray reef shark",
  "gray squirrel",
  "graywolf",
  "great argus",
  "greatdane",
  "great horned owl",
  "great white shark",
  "grebe",
  "green darner dragonfly",
  "greyhound dog",
  "grison",
  "grizzly bear",
  "grosbeak",
  "ground beetle",
  "groundhog",
  "grouper",
  "grouse",
  "grub",
  "grunion",
  "guanaco",
  "guernsey cow",
  "guillemot",
  "guineafowl",
  "guinea pig",
  "gull",
  "guppy",
  "gypsy moth",
  "gyrfalcon",
  "hackee",
  "haddock",
  "hadrosaurus",
  "hagfish",
  "hairstreak",
  "hairstreak butterfly",
  "hake",
  "halcyon",
  "halibut",
  "halicore",
  "hamadryad",
  "hamadryas",
  "hammerhead bird",
  "hammerhead shark",
  "hammerkop",
  "hamster",
  "hanuman monkey",
  "hapuka",
  "hapuku",
  "harbor porpoise",
  "harbor seal",
  "hare",
  "harlequin bug",
  "harp seal",
  "harpyeagle",
  "harrier",
  "harrier hawk",
  "hart",
  "hartebeest",
  "harvestmen",
  "harvest mouse",
  "hatchetfish",
  "hawaiian monk seal",
  "hawk",
  "hector's dolphin",
  "hedgehog",
  "heifer",
  "hellbender",
  "hen",
  "herald",
  "hercules beetle",
  "hermit crab",
  "heron",
  "herring",
  "heterodontosaurus",
  "hind",
  "hippopotamus",
  "hoatzin",
  "hochstetter's frog",
  "hog",
  "hogget",
  "hoiho",
  "hoki",
  "homalocephale",
  "honeybadger",
  "honeybee",
  "honeycreeper",
  "honeyeater",
  "hooker sea lion",
  "hoopoe",
  "hornbill",
  "horned toad",
  "horned viper",
  "hornet",
  "horn shark",
  "horse",
  "horse chestnut leafminer",
  "horsefly",
  "horsemouse",
  "horseshoe bat",
  "horseshoe crab",
  "hound",
  "housefly",
  "hoverfly",
  "howler monkey",
  "huemul",
  "huia",
  "human",
  "hummingbird",
  "humpback whale",
  "husky",
  "hydatid tapeworm",
  "hydra",
  "hyena",
  "hylaeosaurus",
  "hypacrosaurus",
  "hypsilophodon",
  "hyracotherium",
  "hyrax",
  "iaerismetalmark",
  "ibadan malimbe",
  "iberian barbel",
  "iberian chiffchaff",
  "iberian emerald lizard",
  "iberian lynx",
  "iberian midwife toad",
  "iberian mole",
  "iberian nase",
  "ibex",
  "ibis",
  "ibisbill",
  "ibizan hound",
  "ice blue red top zebra",
  "icefish",
  "iceland gull",
  "icelandic horse",
  "icelandic sheepdog",
  "echidna",
  "ichneumon fly",
  "ichthyosaurs",
  "ichthyostega",
  "icterine warbler",
  "iggy pops",
  "iguana",
  "iguanodon",
  "illadopsis",
  "isla mocha degu",
  "imago",
  "impala",
  "imperator angel",
  "imperial eagle",
  "incatern",
  "inchworm",
  "indiana bat",
  "indian cow",
  "indian elephant",
  "indian glassfish",
  "indianhare",
  "indian jackal",
  "indian palm squirrel",
  "indian pangolin",
  "indian rhinoceros",
  "indian ringneck parakeet",
  "indian rock python",
  "indian skimmer",
  "indian spiny loach",
  "indigo bunting",
  "indigo winged parrot",
  "indochina hog deer",
  "indochinese tiger",
  "indri",
  "indus river dolphin",
  "inexpectatus pleco",
  "ingenue",
  "insect",
  "intermediate egret",
  "invisible rail",
  "iranian ground jay",
  "iridescent shark",
  "iriomote cat",
  "irish draught horse",
  "irishredandwhitesetter",
  "irish setter",
  "irish terrier",
  "irish water spaniel",
  "irish wolfhound",
  "irrawaddy dolphin",
  "irukandji jellyfish",
  "isabelline shrike",
  "isabelline wheatear",
  "island canary",
  "island whistler",
  "isopod",
  "italian brown bear",
  "italian greyhound",
  "ivory backed woodswallow",
  "ivory billed woodpecker",
  "ivory gull",
  "izu thrush",
  "jabiru",
  "jackal",
  "jackrabbit",
  "jaeger",
  "jaguar",
  "jaguarundi",
  "janenschia",
  "japanese beetle",
  "javelina",
  "jay",
  "jellyfish",
  "jenny",
  "jerboa",
  "joey",
  "john dory",
  "julia butterfly",
  "jumping bean",
  "junco",
  "junebug",
  "kagu",
  "kakapo",
  "kakarikis",
  "kangaroo",
  "karakul",
  "katydid",
  "kawala",
  "kentrosaurus",
  "kestrel",
  "kid",
  "killdeer",
  "killer whale",
  "killifish",
  "kingbird",
  "kingfisher",
  "kinglet",
  "kingsnake",
  "kinkajou",
  "kiskadee",
  "kissing bug",
  "kite",
  "kitfox",
  "kitten",
  "kittiwake",
  "kitty",
  "kiwi",
  "koala",
  "koala bear",
  "kob",
  "kodiak bear",
  "koi",
  "komodo dragon",
  "koodo",
  "kookaburra",
  "kouprey",
  "krill",
  "kronosaurus",
  "kudu",
  "kusimanse",
  "labrador retriever",
  "lacewing",
  "ladybird",
  "ladybug",
  "lamb",
  "lamprey",
  "langur",
  "lark",
  "larva",
  "laughingthrush",
  "lcont",
  "leafbird",
  "leafcutter ant",
  "leafhopper",
  "leafwing",
  "leech",
  "lemming",
  "lemur",
  "leonberger",
  "leopard",
  "leopard seal",
  "leveret",
  "lhasaapso",
  "lice",
  "liger",
  "lightning bug",
  "limpet",
  "limpkin",
  "ling",
  "lion",
  "lionfish",
  "little night monkeys",
  "lizard",
  "llama",
  "lobo",
  "lobster",
  "locust",
  "loggerhead turtle",
  "longhorn",
  "longhorn beetle",
  "longspur",
  "loon",
  "lorikeet",
  "loris",
  "louse",
  "lovebird",
  "lowchen",
  "luna moth",
  "lungfish",
  "lynx",
  "lynx",
  "macaque",
  "macaw",
  "macropod",
  "madagascar hissing roach",
  "maggot",
  "magpie",
  "maiasaura",
  "majungatholus",
  "malamute",
  "mallard",
  "maltese dog",
  "mamba",
  "mamenchisaurus",
  "mammal",
  "mammoth",
  "manatee",
  "mandrill",
  "mangabey",
  "manta",
  "mantaray",
  "mantid",
  "mantis",
  "manta ray",
  "manx cat",
  "mara",
  "marabou",
  "marbled murrelet",
  "mare",
  "marlin",
  "marmoset",
  "marmot",
  "marten",
  "martin",
  "massasauga",
  "massospondylus",
  "mastiff",
  "mastodon",
  "mayfly",
  "meadowhawk",
  "meadowlark",
  "mealworm",
  "meerkat",
  "megalosaurus",
  "megalotomusquinquespinosus",
  "megaraptor",
  "merganser",
  "merlin",
  "metalmark butterfly",
  "metamorphosis",
  "mice",
  "microvenator",
  "midge",
  "milk snake",
  "milkweed bug",
  "millipede",
  "minibeast",
  "mink",
  "minnow",
  "mite",
  "moa",
  "mockingbird",
  "mole",
  "mollies",
  "mollusk",
  "molly",
  "monarch",
  "mongoose",
  "mongrel",
  "monkey",
  "monkfish",
  "monoclonius",
  "montanoceratops",
  "moorhen",
  "moose",
  "moray",
  "moray eel",
  "morpho",
  "mosasaur",
  "mosquito",
  "moth",
  "motmot",
  "mouflon",
  "mountain cat",
  "mountain lion",
  "mouse",
  "mouse/mice",
  "mousebird",
  "mudpuppy",
  "mule",
  "mullet",
  "muntjac",
  "murrelet",
  "muskox",
  "muskrat",
  "mussaurus",
  "mussel",
  "mustang",
  "mutt",
  "myna",
  "mynah",
  "myotis",
  "nabarlek",
  "nag",
  "naga",
  "nagapies",
  "naked mole rat",
  "nandine",
  "nandoo",
  "nandu",
  "narwhal",
  "narwhale",
  "natterjack toad",
  "nauplius",
  "nautilus",
  "needlefish",
  "needletail",
  "nematode",
  "nene",
  "neon blue guppy",
  "neon blue hermit crab",
  "neon dwarf gourami",
  "neon rainbowfish",
  "neon red guppy",
  "neon tetra",
  "nerka",
  "nettlefish",
  "newfoundland dog",
  "newt",
  "newtnutria",
  "nightcrawler",
  "nighthawk",
  "night heron",
  "nightingale",
  "nightjar",
  "nijsseni dwarf chih lid",
  "nilgai",
  "nine banded armadillo",
  "noctilio",
  "noctule",
  "noddy",
  "noolbenger",
  "northern cardinals",
  "northern elephant seal",
  "northern flying squirrel",
  "northern fur seal",
  "northern hairy nosed wombat",
  "northern pike",
  "northern seahorse",
  "northern spotted owl",
  "norway lobster",
  "norway rat",
  "nubian goat",
  "nudibranch",
  "numbat",
  "nurse shark",
  "nutcracker",
  "nuthatch",
  "nutria",
  "nyala",
  "nymph",
  "ocelot",
  "octopus",
  "okapi",
  "olingo",
  "olm",
  "opossum",
  "orangutan",
  "orca",
  "oregon silverspot butterfly",
  "oriole",
  "oropendola",
  "oropendola",
  "oryx",
  "osprey",
  "ostracod",
  "ostrich",
  "otter",
  "ovenbird",
  "owl",
  "owl butterfly",
  "ox",
  "oxen",
  "oxpecker",
  "oyster",
  "ozark big eared bat",
  "paca",
  "pachyderm",
  "pacific parrotlet",
  "paddlefish",
  "painted lady butterfly",
  "panda",
  "pangolin",
  "panther",
  "paper wasp",
  "papillon",
  "parakeet",
  "parrot",
  "partridge",
  "peacock",
  "peafowl",
  "peccary",
  "pekingese",
  "pelican",
  "pelecinus petrel",
  "penguin",
  "perch",
  "peregrine falcon",
  "pewee",
  "phalarope",
  "pharaoh hound",
  "pheasant",
  "phoebe",
  "phoenix",
  "pig",
  "pigeon",
  "piglet",
  "pika",
  "pike",
  "pikeperch",
  "pilchard",
  "pine marten",
  "pink river dolphin",
  "pinniped",
  "pintail",
  "pipistrelle",
  "pipit",
  "piranha",
  "pitbull",
  "pitta bird",
  "plain squeaker",
  "plankton",
  "planthopper",
  "platypus",
  "plover",
  "polarbear",
  "polecat",
  "polliwog",
  "polyp",
  "polyturator",
  "pomeranian",
  "pondskater",
  "pony",
  "pooch",
  "poodle",
  "porcupine",
  "porpoise",
  "portuguese man of war",
  "possum",
  "prairie dog",
  "prawn",
  "praying mantis",
  "praying mantis",
  "primate",
  "pronghorn",
  "pseudo dynerusquadrisectus",
  "ptarmigan",
  "pterodactyls",
  "pterosaurs",
  "puffer",
  "pufferfish",
  "puffin",
  "pug",
  "pullet",
  "puma",
  "pupa",
  "pupfish",
  "puppy",
  "purple martin",
  "pussycat",
  "pygmy",
  "python",
  "quadrisect",
  "quagga",
  "quahog",
  "quail",
  "queen alexandra's birdwing",
  "queen alexandra's birdwing butterfly",
  "queenant",
  "queenbee",
  "queen conch",
  "queensland grouper",
  "queensland heeler",
  "queensnake",
  "quelea",
  "quetzal",
  "quetzalcoatlus",
  "quillback",
  "quinquespinosus",
  "quokka",
  "quoll",
  "rabbit",
  "rabid squirrel",
  "raccoon",
  "racer",
  "racerunner",
  "ragfish",
  "rail",
  "rainbowfish",
  "rainbow lorikeet",
  "rainbow trout",
  "ram",
  "raptors",
  "rasbora",
  "rat",
  "ratfish",
  "rattail",
  "rattlesnake",
  "raven",
  "ray",
  "redhead",
  "red headed woodpecker",
  "redpoll",
  "redstart",
  "red tailed hawk",
  "reindeer",
  "reptile",
  "reynard",
  "rhea",
  "rhesus monkey",
  "rhino",
  "rhinoceros",
  "rhinoceros beetle",
  "rhodesian ridgeback",
  "ring tailed lemur",
  "ringworm",
  "río grande escuerzo",
  "roach",
  "roadrunner",
  "roan",
  "robber fly",
  "robin",
  "rockrat",
  "rodent",
  "roebuck",
  "roller",
  "rook",
  "rooster",
  "rottweiler",
  "sable",
  "sable antelope",
  "sablefish",
  "saiga",
  "saki monkey",
  "salamander",
  "salmon",
  "saltwater crocodile",
  "sambar",
  "samoyed dog",
  "sandbar shark",
  "sanddollar",
  "sanderling",
  "sandpiper",
  "sapsucker",
  "sardine",
  "sawfish",
  "scallop",
  "scarab",
  "scarlet ibis",
  "scaup",
  "schapendoes",
  "schipperke",
  "schnauzer",
  "scorpion",
  "scoter",
  "screamer",
  "seabird",
  "seagull",
  "seahog",
  "seahorse",
  "seal",
  "sealion",
  "seamonkey",
  "sea slug",
  "sea urchin",
  "senegal python",
  "seriema",
  "serpent",
  "serval",
  "shark",
  "shearwater",
  "sheep",
  "sheldrake",
  "shelduck",
  "shiba inu",
  "shih tzu",
  "shorebird",
  "shoveler",
  "shrew",
  "shrike",
  "shrimp",
  "siamang",
  "siamese cat",
  "siberian tiger",
  "sidewinder",
  "sifaka",
  "silkworm",
  "silverfish",
  "silverfox",
  "silverside fish",
  "siskin",
  "skimmer",
  "skink",
  "skipper",
  "skua",
  "skunk",
  "skylark",
  "sloth",
  "sloth bear",
  "slug",
  "smelts",
  "smew",
  "snail",
  "snake",
  "snipe",
  "snout butterfly",
  "snowdog",
  "snow geese",
  "snow leopard",
  "snow monkey",
  "snowy owl",
  "sockeye salmon",
  "solenodon",
  "solitaire",
  "songbird",
  "sora",
  "southern hairy nosed wombat",
  "sow",
  "spadefoot",
  "sparrow",
  "sphinx",
  "spider",
  "spidermonkey",
  "spiketail",
  "spittlebug",
  "sponge",
  "spoonbill",
  "spotted dolphin",
  "spreadwing",
  "springbok",
  "spring peeper",
  "springtail",
  "squab",
  "squamata",
  "squeaker",
  "squid",
  "squirrel",
  "stag",
  "stag beetle",
  "stallion",
  "starfish",
  "starling",
  "steed",
  "steer",
  "stegosaurus",
  "stick insect",
  "stickleback",
  "stilt",
  "stingray",
  "stink bug",
  "stinkpot",
  "stoat",
  "stonefly",
  "stork",
  "stud",
  "sturgeon",
  "sugarglider",
  "sulphur butterfly",
  "sunbear",
  "sunbittern",
  "sunfish",
  "swallow",
  "swallowtail",
  "swallowtail butterfly",
  "swan",
  "swellfish",
  "swift",
  "swordfish",
  "tadpole",
  "tahr",
  "takin",
  "tamarin",
  "tanager",
  "tapaculo",
  "tapeworm",
  "tapir",
  "tarantula",
  "tarpan",
  "tarsier",
  "taruca",
  "tasmanian devil",
  "tasmanian tiger",
  "tattler",
  "tayra",
  "teal",
  "tegus",
  "teledu",
  "tench",
  "tenrec",
  "termite",
  "tern",
  "terrapin",
  "terrier",
  "thoroughbred",
  "thrasher",
  "thrip",
  "thrush",
  "thunderbird",
  "thylacine",
  "tick",
  "tiger",
  "tiger beetle",
  "tigermoth",
  "tigershark",
  "tilefish",
  "tinamou",
  "titi",
  "titmouse",
  "toad",
  "toadfish",
  "tomtit",
  "topi",
  "tortoise",
  "toucan",
  "towhee",
  "tragopan",
  "treecreeper",
  "trex",
  "triceratops",
  "trogon",
  "trout",
  "trumpeter bird",
  "trumpeter swan",
  "tsetse fly",
  "tuatara",
  "tuna",
  "turaco",
  "turkey",
  "turnstone",
  "turtle",
  "turtledove",
  "uakari",
  "uganda kob",
  "uinta ground squirrel",
  "ulysses butterfly",
  "umbrellabird",
  "umbrette",
  "unau",
  "ungulate",
  "unicorn",
  "upupa",
  "urchin",
  "urial",
  "uromastyx maliensis",
  "uromastyx spinipes",
  "urson",
  "urubu",
  "urus",
  "urutu",
  "urva",
  "utah prairie dog",
  "vampire bat",
  "vaquita",
  "veery",
  "velociraptor",
  "velvet crab",
  "velvet worm",
  "venomous snake",
  "verdin",
  "vervet",
  "viceroy butterfly",
  "vicuna",
  "viper",
  "viperfish",
  "viper squid",
  "vireo",
  "virginia opossum",
  "vixen",
  "vole",
  "volvox",
  "vulpes velox",
  "vulpes vulpes",
  "vulture",
  "walkingstick",
  "wallaby",
  "wallaroo",
  "walleye",
  "walrus",
  "warbler",
  "warthog",
  "wasp",
  "water boatman",
  "waterbuck",
  "water buffalo",
  "waterbug",
  "waterdogs",
  "water dragons",
  "water moccasin",
  "waterstrider",
  "waterthrush",
  "wattlebird",
  "watussi",
  "waxwing",
  "weasel",
  "weaverbird",
  "weevil",
  "west african antelope",
  "whale",
  "whapuku",
  "whelp",
  "whimbrel",
  "whippet",
  "whippoorwill",
  "white beaked dolphin",
  "white eye",
  "white pelican",
  "white rhino",
  "white tailed deer",
  "white tipped reef shark",
  "whooper",
  "whooping crane",
  "widgeon",
  "widow spider",
  "wildcat",
  "wildebeest",
  "wildebeest",
  "willet",
  "wireworm",
  "wisent",
  "wobbegong shark",
  "wolf",
  "wolf spider",
  "wolverine",
  "wombat",
  "wood borer",
  "woodchuck",
  "woodcock",
  "wood nymph butterfly",
  "woodpecker",
  "woodstorks",
  "woolly bear caterpillar",
  "worm",
  "wrasse",
  "wreckfish",
  "wren",
  "wrenchbird",
  "wryneck",
  "wuerhosaurus",
  "wyvern",
  "xanclomys",
  "xanthareel",
  "xantus",
  "xantus murrelet",
  "xeme",
  "xenarthra",
  "xenoposeidon",
  "xenops",
  "neopterygii",
  "xenopus",
  "xenotarsosaurus",
  "xenurine",
  "xenurus unicinctus",
  "xerus",
  "xiaosaurus",
  "xinjiangovenator",
  "xiphias",
  "xiphias gladius",
  "xiphosura",
  "xoloitzcuintli",
  "xoni",
  "x-ray fish",
  "x-ray tetra",
  "xuanhanosaurus",
  "xuanhuaceratops",
  "xuanhanosaurus",
  "yaffle",
  "yak",
  "yapok",
  "yardant",
  "yearling",
  "yellow bellied marmot",
  "yellow belly lizard",
  "yellowhammer",
  "yellowjacket",
  "yellowlegs",
  "yellowthroat",
  "yellow white butterfly",
  "yeti",
  "ynambu",
  "yorkshire terrier",
  "yosemite toad",
  "yucker",
  "zander",
  "zanzibar day gecko",
  "zebra",
  "zebra dove",
  "zebra finch",
  "zebrafish",
  "zebra longwing butterfly",
  "zebra swallowtail butterfly",
  "zebra tailed lizard",
  "zebu",
  "zenaida",
  "zeren",
  "zethus spinipes",
  "zethus wasp",
  "zigzag salamander",
  "zone tailed pigeon",
  "zooplankton",
  "zopilote",
  "zorilla"
];
